Сделал сетку главной страницы
htmlacademy-htmlcss/28451-sedona-29 pull request #6
Opened 2020-10-07 03:47 UTC by Junfrontend

2020-10-08 10:22 UTC, KupperXD requested changes

2020-10-08 10:22 UTC, KupperXD commented on css/style.css
> +  width: 1200px;
Ты задал ширину но не цинтрировал контент по центру экрана. Самый простой способ отцентрировать контент с заданной шириной это margin: 0 auto; Так же не нужно body - ограничивать по ширине. так как тебе нужна вся ширина экрана. Ограничивать надо внутренни секционные блоки. Так как размер у нас фиксированный. Ты можешь создать класс .container - задать ему ширину и центровку, и вешать этот класс на секционные блоки которые ты хочешь ограничить по ширине. Например на main. Но чаще всего делают дополнитульную обёртку - div с классом container и внутри него уже весь контент.

2020-10-08 10:22 UTC, KupperXD commented on index.html
> +          <div class="small-feature">
Тут нельзя оборачивать в div - должна быть li а потом внутри уже что то другое. И тут можно было обойтись, глобальной сеткой на ul - и задавать сетку li. Тут можно сделать трёх колоночную сетку, и по стандарту item занимает одну колонку, так же сделать дополнительный класс item--ful-column - и если есть такой класс, то пускай li занимает не одну колонку, а все имеющиешся, тогда она просто займется три колонки, а остальные элементы перенесутся на следуюущую строку. Твой вариант подходит для flex - так как там пришлось бы делать дополнительную обёртку.

2020-10-17 15:13 UTC, Junfrontend commented
Исправил замечания.

2020-10-19 06:55 UTC, merged